; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.0"

projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc3"

projects[admin_views][subdir] = "contrib"
projects[admin_views][version] = "1.0"

projects[advanced_help][subdir] = "contrib"
projects[advanced_help][version] = "1.0"

projects[backup_migrate][subdir] = "contrib"
projects[backup_migrate][version] = "2.4"

projects[blockreference][subdir] = "contrib"
projects[blockreference][version] = "1.13"

projects[cck_blocks][subdir] = "contrib"
projects[cck_blocks][version] = "1.1"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.2"

projects[context][subdir] = "contrib"
projects[context][version] = "3.0-beta4"

projects[context_menu_block][subdir] = "contrib"
projects[context_menu_block][version] = "3.1-beta2"

projects[date][subdir] = "contrib"
projects[date][version] = "2.6"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.3"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[draggableviews][subdir] = "contrib"
projects[draggableviews][version] = "2.0"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.0-rc3"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.0-rc5"

projects[eva][subdir] = "contrib"
projects[eva][version] = "1.2"

projects[features_extra][subdir] = "contrib"
projects[features_extra][version] = "1.0-alpha1"

projects[features][subdir] = "contrib"
projects[features][version] = "1.0"

projects[field_collection][subdir] = "contrib"
projects[field_collection][version] = "1.0-beta4"

projects[geocoder_autocomplete][subdir] = "contrib"
projects[geocoder_autocomplete][version] = "1.x-dev"

projects[i18n][subdir] = "contrib"
projects[i18n][version] = "1.7"

projects[insert][subdir] = "contrib"
projects[insert][version] = "1.2"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.3-alpha1+0-dev"

projects[l10n_client][subdir] = "contrib"
projects[l10n_client][version] = "1.1"

projects[l10n_update][subdir] = "contrib"
projects[l10n_update][version] = "1.0-beta3"

projects[link][subdir] = "contrib"
projects[link][version] = "1.0"

projects[menu_block][subdir] = "contrib"
projects[menu_block][version] = "2.3+7-dev"

projects[menu_import][subdir] = "contrib"
projects[menu_import][version] = "1.2"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "1.7"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[token][subdir] = "contrib"
projects[token][version] = "1.4"

projects[transliteration][subdir] = "contrib"
projects[transliteration][version] = "3.1"

projects[variable][subdir] = "contrib"
projects[variable][version] = "2.1"

projects[video_embed_field][subdir] = "contrib"
projects[video_embed_field][version] = "2.0-beta5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.5"

projects[votingapi][subdir] = "contrib"
projects[votingapi][version] = "2.9"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"

; Themes
projects[mothership][subdir] = "mothership"
projects[mothership][version] = "2.8"



